config/routes.rb
LMFAOParty::Application.routes.draw do
  resources :lmfa_media

  resources :media

   root :to => 'pages#index'
   match '/ph' => 'pages#powerHour'

end

app/models/lmfa_medium.rb
class LmfaMedium < ActiveRecord::Base
end

app/models/medium.rb
class Medium < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lmfa_media_controller.rb
class LmfaMediaController < ApplicationController
  # GET /lmfa_media
  # GET /lmfa_media.json
  def index
    @lmfa_media = LmfaMedium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lmfa_media.shuffle }
    end
  end

  # GET /lmfa_media/1
  # GET /lmfa_media/1.json
  def show
    @lmfa_medium = LmfaMedium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lmfa_medium }
    end
  end

  # GET /lmfa_media/new
  # GET /lmfa_media/new.json
  def new
    @lmfa_medium = LmfaMedium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lmfa_medium }
    end
  end

  # GET /lmfa_media/1/edit
  def edit
    @lmfa_medium = LmfaMedium.find(params[:id])
  end

  # POST /lmfa_media
  # POST /lmfa_media.json
  def create
    @lmfa_medium = LmfaMedium.new(params[:lmfa_medium])

    respond_to do |format|
      if @lmfa_medium.save
        format.html { redirect_to @lmfa_medium, notice: 'Lmfa medium was successfully created.' }
        format.json { render json: @lmfa_medium, status: :created, location: @lmfa_medium }
      else
        format.html { render action: "new" }
        format.json { render json: @lmfa_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lmfa_media/1
  # PUT /lmfa_media/1.json
  def update
    @lmfa_medium = LmfaMedium.find(params[:id])

    respond_to do |format|
      if @lmfa_medium.update_attributes(params[:lmfa_medium])
        format.html { redirect_to @lmfa_medium, notice: 'Lmfa medium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lmfa_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lmfa_media/1
  # DELETE /lmfa_media/1.json
  def destroy
    @lmfa_medium = LmfaMedium.find(params[:id])
    @lmfa_medium.destroy

    respond_to do |format|
      format.html { redirect_to lmfa_media_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  # GET /media
  # GET /media.json
  def index
    @media = Medium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media.shuffle }
    end
  end

  # GET /media/1
  # GET /media/1.json
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/new
  # GET /media/new.json
  def new
    @medium = Medium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render json: @medium, status: :created, location: @medium }
      else
        format.html { render action: "new" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.json
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def powerHour

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lmfa_media_helper.rb
module LmfaMediaHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LMFAOParty</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lmfa_media/_form.html.erb
<%= form_for(@lmfa_medium) do |f| %>
  <% if @lmfa_medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lmfa_medium.errors.count, "error") %> prohibited this lmfa_medium from being saved:</h2>

      <ul>
      <% @lmfa_medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :src %><br />
    <%= f.text_field :src %>
  </div>
  <div class="field">
    <%= f.label :played %><br />
    <%= f.check_box :played %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lmfa_media/edit.html.erb
<h1>Editing lmfa_medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @lmfa_medium %> |
<%= link_to 'Back', lmfa_media_path %>

app/views/lmfa_media/index.html.erb
<h1>Listing lmfa_media</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Src</th>
    <th>Played</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lmfa_media.each do |lmfa_medium| %>
  <tr>
    <td><%= lmfa_medium.name %></td>
    <td><%= lmfa_medium.src %></td>
    <td><%= lmfa_medium.played %></td>
    <td><%= link_to 'Show', lmfa_medium %></td>
    <td><%= link_to 'Edit', edit_lmfa_medium_path(lmfa_medium) %></td>
    <td><%= link_to 'Destroy', lmfa_medium, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lmfa medium', new_lmfa_medium_path %>

app/views/lmfa_media/new.html.erb
<h1>New lmfa_medium</h1>

<%= render 'form' %>

<%= link_to 'Back', lmfa_media_path %>

app/views/lmfa_media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lmfa_medium.name %>
</p>


<p>
  <b>Played:</b>
  <%= @lmfa_medium.played %>
</p>

<video src="/assets/lmfaoMedia/<%= @lmfa_medium.src %>" width="800" autoplay> </video>

<%= link_to 'Edit', edit_lmfa_medium_path(@lmfa_medium) %> |
<%= link_to 'Back', lmfa_media_path %>

app/views/media/_form.html.erb
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :src %><br />
    <%= f.text_field :src %>
  </div>
  <div class="field">
    <%= f.label :played %><br />
    <%= f.check_box :played %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Src</th>
    <th>Played</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @media.each do |medium| %>
  <tr>
    <td><%= medium.name %></td>
    <td><%= medium.src %></td>
    <td><%= medium.played %></td>
    <td><%= link_to 'Show', medium %></td>
    <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
    <td><%= link_to 'Destroy', medium, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medium.name %>
</p>
<p>
  <b>Played:</b>
  <%= @medium.played %>
</p>
<video src="/assets/media/<%= @medium.src %>" autoplay> </video>


<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/pages/index.html.erb
<video id="video" autoplay style="display:none" ></video> 
<div id="timeLeft">
  <span></span>
</div>
<script type="text/javascript">

  var songType = 'lmfa_media';

  function playSong(song) {
    $("video").attr("src",'/assets/lmfaoMedia/'+song.src)
  }

  $(function() {
      (function updateTime() {
       var time = new Date(),
       mLeft = 59 - time.getMinutes(),
       sLeft = 59 - time.getSeconds(),
       milliLeft = 1000 - time.getMilliseconds();
       $("#timeLeft span").text(mLeft+":"+sLeft+"."+milliLeft);
       if(mLeft == 0 && sLeft == 0) {
         window.location = "/ph";
        return;
       }
       setTimeout(updateTime, 10);
       })()
      })

if ( ! Detector.webgl ) Detector.addGetWebGLMessage();

var container;

var camera, scene, renderer;

var video, texture, material, mesh;

var composer;

var mouseX = 0;
var mouseY = 0;
var mouseDest = {dx:5, dy:5, x:0, y:0, done:true}

var windowHalfX = window.innerWidth / 2;
var windowHalfY = window.innerHeight / 2;

var particleSystems = [],
  particleCount = 50,
  particleSets = []; 
  //particles = new THREE.Geometry();

var cube_count,

    meshes = [],
    materials = [],

    xgrid = 20,
    ygrid = 10;

init();
animate();

function init() {

  container = document.createElement( 'div' );
  document.body.appendChild( container );

  scene = new THREE.Scene();

  camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 10000 );
  camera.position.z = 500;
  scene.add( camera );

  var light = new THREE.DirectionalLight( 0xffffff );
  light.position.set( 0.5, 1, 1 ).normalize();
  scene.add( light );

  // Particles!
  // create the particle variables
      // create the particle variables
  var pMaterials = [];

  pMaterials.push(
  new THREE.ParticleBasicMaterial({
    color: 0xFFFFFF,
    size: 50,
    map: THREE.ImageUtils.loadTexture(
      "assets/particle.png"
    ),
    blending: THREE.AdditiveBlending,
    transparent: true
  }),
  new THREE.ParticleBasicMaterial({
    color: 0xFFFFFF,
    size: 150,
    map: THREE.ImageUtils.loadTexture(
      "assets/particle2.png"
    ),
    blending: THREE.AdditiveBlending,
    transparent: true
  }))


  for(var pm = 0;pm < pMaterials.length;pm++) {
  particleSets.push(new THREE.Geometry());
  var particles = particleSets[pm];
// now create the individual particles
for(var p = 0; p < particleCount; p++) {
  // create a particle with random
  // position values, -250 -> 250
  var pX = Math.random() * 1000 - 500,
      pY = Math.random() * 1000 - 500,
      pZ = Math.random() * 1000 - 500,
      particle = new THREE.Vertex(
          new THREE.Vector3(pX, pY, pZ)
          );

  // Apply random (negative) y velocity to particles so they appear to be falling
  particle.velocity = new THREE.Vector3(0,-Math.random(),0);

  // add it to the geometry
  particles.vertices.push(particle);
}

// create the particle system
particleSystems.push(
new THREE.ParticleSystem(
    particles,
    pMaterials[pm])
)

// also update the particle system to
// sort the particles which enables
// the behaviour we want
particleSystems[pm].sortParticles = true;

// add it to the scene
scene.add(particleSystems[pm]);
}
// END particles!


renderer = new THREE.WebGLRenderer( { antialias: false } );
renderer.setSize( window.innerWidth, window.innerHeight );

container.appendChild( renderer.domElement );

video = document.getElementById( 'video' );

texture = new THREE.Texture( video );
texture.minFilter = THREE.LinearFilter;
texture.magFilter = THREE.LinearFilter;
texture.format = THREE.RGBFormat;

var i, j, ux, uy, ox, oy,
    geometry,
    xsize, ysize;

ux = 1 / xgrid;
uy = 1 / ygrid;

xsize = 480 / xgrid;
ysize = 204 / ygrid;

var parameters = { color: 0xffffff, map: texture },
    material_base = new THREE.MeshLambertMaterial( parameters );

renderer.initMaterial( material_base, scene.__lights, scene.fog );

cube_count = 0;

for ( i = 0; i < xgrid; i ++ )
for ( j = 0; j < ygrid; j ++ ) {

  ox = i;
  oy = j;

  geometry = new THREE.CubeGeometry( xsize, ysize, xsize );
  change_uvs( geometry, ux, uy, ox, oy );

  materials[ cube_count ] = new THREE.MeshLambertMaterial( parameters );

  material = materials[ cube_count ];

  mesh = new THREE.Mesh( geometry, material );

  mesh.position.x =   ( i - xgrid/2 ) * xsize;
  mesh.position.y = - ( j - ygrid/2 ) * ysize;
  mesh.position.z = 0;

  mesh.scale.x = mesh.scale.y = mesh.scale.z = 1;

  scene.add(mesh);

  mesh.dx = Math.random() < .5 ? 0.001 * ( 0.5- Math.random() ) : 0;
  mesh.dy = 0.001 * ( 0.5 - Math.random() );

  meshes[ cube_count ] = mesh;

  cube_count += 1;

}

renderer.autoClear = false;

// postprocessing

var renderModel = new THREE.RenderPass( scene, camera );
var effectBloom = new THREE.BloomPass( 1.3 );
var effectScreen = new THREE.ShaderPass( THREE.ShaderExtras[ "screen" ] );

effectScreen.renderToScreen = true;

composer = new THREE.EffectComposer( renderer );

composer.addPass( renderModel );
composer.addPass( effectBloom );
composer.addPass( effectScreen );

}

function change_uvs( geometry, unitx, unity, offsetx, offsety ) {

  var i, j, uv;

  for ( i = 0; i < geometry.faceVertexUvs[ 0 ].length; i++ ) {

    uv = geometry.faceVertexUvs[ 0 ][ i ];

    for ( j = 0; j < uv.length; j++ ) {

      uv[j].u = ( uv[j].u + offsetx ) * unitx;
      uv[j].v = ( uv[j].v + offsety ) * unity;

    }

  }

}


function randomMouseMove() {
  if(mouseDest.done) {
    mouseDest.x = windowHalfX/2*-1 + Math.floor(Math.random() * windowHalfX);
    mouseDest.y = windowHalfY/2*-1 + Math.floor(Math.random() * windowHalfY);
    mouseDest.done = false;

    var xdist = mouseDest.x - mouseX;
    var ydist = mouseDest.y - mouseY;
    mouseDest.dx = xdist/50;
    mouseDest.dy = ydist/50;
  } 

  mouseX += mouseDest.dx;
  mouseY += mouseDest.dy;

  var xdist = Math.abs(mouseX - mouseDest.x);
  var ydist = Math.abs(mouseY - mouseDest.y);
  if(xdist < 5 && ydist < 5) {
    mouseDest.done = true;
  }

}

//

function animate() {

  requestAnimationFrame( animate );

  render();

}

var h, counter = 1;

function render() {
  randomMouseMove()

  var time = Date.now() * 0.00005;

  camera.position.x += ( mouseX - camera.position.x ) * 0.05;
  camera.position.y += ( - mouseY - camera.position.y ) * 0.05;

  camera.lookAt( scene.position );

  if ( video.readyState === video.HAVE_ENOUGH_DATA ) {

    if ( texture ) texture.needsUpdate = true;

  }

  //particles!
  for(var pi=0;pi<particleSystems.length;pi++){
  particleSystems[pi].rotation.y += 0.01;

  var pCount = particleSets[pi].vertices.length,
      particles = particleSets[pi];

    while(pCount--) {
      var particle = particles.vertices[pCount];

      // Reset particles that fall too low
      if(particle.position.y < -200) {
        particle.position.y = 200;
        particle.velocity.y = 0;
      }

      particle.velocity.y -= Math.random() *.1;

      particle.position.addSelf(particle.velocity);
    }
    particleSystems[pi].geometry.__dirtyVertices = true;

  // END particles
  }


  for( i = 0; i < cube_count; i++ ) {

    material = materials[i];

    h = ( 360 * ( material.hue + time ) % 360 ) / 360;
    material.color.setHSV( h, material.saturation, 1 );

  }

  if(counter % 2000 > 1000) {
    //Once the pieces are back, reset each dx
    if (counter % 1000 == 0 ) {

      for( i = 0; i < cube_count; i++ ) {
        mesh = meshes[i];
        mesh.dx = Math.random() < .5 ? 0.001 * ( 0.5- Math.random() ) : 0;
      }

    }

    if( counter % 500  > 50 ) {

      for( i = 0; i < cube_count; i++ ) {

        mesh = meshes[i];

        mesh.position.y += 100 * mesh.dx;
        mesh.position.x += 100* mesh.dx;
        mesh.position.z += 500 * mesh.dx;
        mesh.rotation.x += 10 * mesh.dx;
        mesh.rotation.y += 10 * mesh.dx;

      }

    } 

    if( counter % 500  == 0 ) {

      for( i = 0; i < cube_count; i++ ) {

        mesh = meshes[i];

        mesh.dx *= -1;
        mesh.dy *= -1;

      }

    } 

  }

  counter ++;

  renderer.clear();
  composer.render();


}
</script>

app/views/pages/ph.html.erb
<div style="position:absolute;top:0;left:0;background:#efefef;z-index:99999;height:200px;">
  <a href="/ph" >Show Power Hour </a><br />
  <a href="/" >Show Video</a>
</div>
<div id="PowerHour">
  <div id="PHheader"></div>
    <h1>Time:<span id="time"></span></h1>
    <div id="phVid" style="width:700px;height:700px;overflow:hidden;margin:0 auto;position:relative;z-index:100;">
      <canvas height="700" width="700" id="canvas"></canvas>

      <video id="phVideo" style="margin-left:-200px;margin-top:50px;z-index:1;" src="media/fuckyou.m4v" height="600" width="1100">
      </video>
    </div>
</div>

<script type="text/javascript">
  Array.prototype.shuffle = function(){ //v1.0
  for(var j, x, i = this.length; i; j = parseInt(Math.random() * i), x = this[--i], this[i] = this[j], this[j] = x);
};

var q = [
  {name:"fuckyou.m4v",mask:1},
  {name:"Hello.m4v",mask:2},
  {name:"CrazyBitch.m4v", mask:1}
]

$(function() {
  q.shuffle();
})  

var start;
function initPowerHour() {
  start = new Date();
  updateClock();
  //Load the first video
  loadVid();
}


function loadVid() {
  //Grab the next video
  var vid = q.shift();

  //Grab a random location in that video > 60 seconds from the end
  $("#phVideo").attr("src","/assets/media/"+vid.name).removeClass("mask1 mask2").addClass("mask"+vid.mask);
  var htmlvid = $("#phVideo").get(0);
  (function vidCheck() {
    if(htmlvid.readyState > 0) {
      var d = htmlvid.duration,
      start = Math.random() * (d-60);
      htmlvid.currentTime = start;
      htmlvid.play()
    } else {
      setTimeout(vidCheck, 10)
    }
  })()

}

function updateClock() {
  var now = new Date();
  var diff = (now - start)/1000%60;
  var arc = diff/60 * Math.PI * 2;
  $("#time").text(Math.floor(diff));
  drawPowerHour(arc)

  setTimeout(updateClock, 10);
}

function drawPowerHour(a) {
  var canvas = document.getElementById("canvas");
  var arc = a || 0;

  if (canvas.getContext) {
    var outsideRadius = 322;

    ctx = canvas.getContext("2d");
    ctx.clearRect(0,0,700,700);


    ctx.strokeStyle = "#84f078";
    ctx.lineWidth = 50;

    ctx.font = 'bold 30px Helvetica, Arial';


    ctx.fillStyle = "#84f078";
    ctx.beginPath();
    ctx.arc(350, 350, outsideRadius, 0, arc);
    ctx.stroke();
    return;
    for(var i = 0; i < 100; i++) {
      var angle = startAngle + i * arc;
      ctx.fillStyle = colors[(i%2)];

      ctx.beginPath();
      ctx.arc(500, 500, outsideRadius, angle, angle + arc, false);
      ctx.arc(500, 500, insideRadius, angle + arc, angle, true);
      ctx.stroke();
      ctx.fill();

      ctx.save();
      ctx.shadowOffsetX = -1;
      ctx.shadowOffsetY = -1;
      ctx.shadowBlur    = 0;
      ctx.shadowColor   = "rgb(220,220,220)";
      ctx.fillStyle = colors2[(i%2)];
      ctx.translate(500 + Math.cos(angle + arc / 2) * textRadius, 
                    500 + Math.sin(angle + arc / 2) * textRadius);
                    ctx.rotate(angle + arc / 2 + Math.PI / 2);
                    var text = fuckYou.penalties[i].abrev;
                    ctx.fillText(text, -ctx.measureText(text).width / 2, 0);
                    ctx.restore();
    } 

  }
}
</script>

app/views/pages/powerHour.html.erb
<div id="PowerHour">
  <div id="PHheader"></div>
  <div id="phContent">
    <div id="phVid" style="width:700px;height:700px;overflow:hidden;margin:0 auto;position:relative;z-index:100;">
      <div style="display:none" id="drinkBitch"></div>
      <canvas height="700" width="700" id="canvas"></canvas>

      <video id="phVideo" style="margin-left:-200px;margin-top:50px;z-index:1;" src="media/fuckyou.m4v" height="600" width="1100">
      </video>
    </div>
    <div id="counter">
      <div class="one"></div>
    </div>
</div>
</div>

<script type="text/javascript">
var exceptions = {
  "Hello.m4v": "mask2",
}
var nums = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
var count = 0;
var ready = false;
var songType = "media";

$(function() {
  setTimeout(function() { ready = true;}, 30000)
  start = new Date();
  updateClock();
})  

var start;
function playSong(song) {
  if(count == 10) {
    window.location = "/";
    return;
  }

  //Show the drink sign! and Fade it out
  $("#drinkBitch").fadeIn("fast");
  setTimeout(function() { $("#drinkBitch").fadeOut("slow")}, 5000)
  
  count++;

  //Update the count
  $("#counter div").attr("class",nums[count]);
  //Grab a random location in that video > 60 seconds from the end
  $("#phVideo").attr("src","/assets/media/"+song.src).attr("class","");
  if(exceptions[song.src]) {
    $("#phVideo").addClass(exceptions[song.src]);
  } else {
    $("#phVideo").addClass("mask1");
  }

  var htmlvid = $("#phVideo").get(0);
  (function vidCheck() {
    if(htmlvid.readyState > 0) {
      var d = htmlvid.duration,
      start = Math.random() * (d-60);
      htmlvid.currentTime = 60;
      htmlvid.play()
    } else {
      setTimeout(vidCheck, 10)
    }
  })()

}

function updateClock() {
  var now = new Date();
  var diff = (now - start)/1000%60;
  var arc = diff/60 * Math.PI * 2;
  if(ready && Math.round(diff) === 0) {
    ready = false;
    setTimeout(function() { ready = true;}, 30000)
    nextSong()
  }
  drawPowerHour(arc)

  setTimeout(updateClock, 10);
}

function drawPowerHour(a) {
  var canvas = document.getElementById("canvas");
  var arc = a || 0;

  if (canvas.getContext) {
    var outsideRadius = 322;
    
    ctx = canvas.getContext("2d");
    ctx.clearRect(0,0,700,700);


    ctx.strokeStyle = "#84f078";
    ctx.lineWidth = 50;

    ctx.font = 'bold 30px Helvetica, Arial';


    ctx.fillStyle = "#84f078";
    ctx.beginPath();
    ctx.arc(350, 350, outsideRadius, 0, arc);
    ctx.stroke();

    ctx.beginPath();
    ctx.lineWidth = 20;
    ctx.strokeStyle = "#e84ca5";
    ctx.arc(350, 350, outsideRadius, 0, arc);
    ctx.stroke();
    return;
    for(var i = 0; i < 100; i++) {
      var angle = startAngle + i * arc;
      ctx.fillStyle = colors[(i%2)];

      ctx.beginPath();
      ctx.arc(500, 500, outsideRadius, angle, angle + arc, false);
      ctx.arc(500, 500, insideRadius, angle + arc, angle, true);
      ctx.stroke();
      ctx.fill();

      ctx.save();
      ctx.shadowOffsetX = -1;
      ctx.shadowOffsetY = -1;
      ctx.shadowBlur    = 0;
      ctx.shadowColor   = "rgb(220,220,220)";
      ctx.fillStyle = colors2[(i%2)];
      ctx.translate(500 + Math.cos(angle + arc / 2) * textRadius, 
                    500 + Math.sin(angle + arc / 2) * textRadius);
                    ctx.rotate(angle + arc / 2 + Math.PI / 2);
                    var text = fuckYou.penalties[i].abrev;
                    ctx.fillText(text, -ctx.measureText(text).width / 2, 0);
                    ctx.restore();
    } 

  }
}
</script>